version: 0.0
os: linux
fileExistsBehavior: OVERWRITE
files:
  - source: /
    destination: /home/ubuntu/weather-app
    except: 
      - scripts/**
      - package-lock.json
permissions:
  - object: /home/ubuntu/weather-app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
